using System.IO;
using System.Linq;

namespace HomeAssistantApps;

[NetDaemonApp]
public class GenerateRecorderYaml
{
    private const string OutputPath = "/config/recorder.yaml";
    private readonly ILogger<GenerateRecorderYaml> _logger;
    private readonly IHaRegistry _haRegistry;

    public GenerateRecorderYaml(IHaRegistry haRegistry, InputButtonEntities buttonEntities, ILogger<GenerateRecorderYaml> logger)
    {
        _logger = logger;
        _haRegistry = haRegistry;

        buttonEntities.GenerateRecorderYaml.StateChanges().Subscribe(_ => GenerateConfig());
    }

    private void GenerateConfig()
    {
        try
        {
            _logger.LogInformation("Starting Recorder YAML generation...");

            var entityConfigs = new System.Text.StringBuilder();
            var entities = _haRegistry?.GetLabel("expose_to_recorder")?.Entities?.ToList();
            
            if (entities != null)
            {
                foreach (var entity in entities)
                {
                    entityConfigs.AppendLine($"- {entity.EntityId}");
                }
            }

            // 4. Construct Final YAML
            var yamlContent = $@"# AUTOMATICALLY GENERATED BY NETDAEMON. DO NOT EDIT.
{entityConfigs}
";

            File.WriteAllText(OutputPath, yamlContent);
#pragma warning disable CA1873 // Avoid potentially expensive logging
            _logger.LogInformation("Successfully wrote {Count} entities to {Path}", entities?.Count, OutputPath);
#pragma warning restore CA1873 // Avoid potentially expensive logging
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to generate Recorder YAML");
        }
    }
}